server:
  port: ${SERVER_PORT:8003}

spring:
  application:
    name: carrier-mock-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true