apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.7
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yaml"
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8001
              name: admin
---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: LoadBalancer
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
