apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - order-service/deployment.yaml
  - order-service/service.yaml
  - shipment-integration-service/deployment.yaml
  - shipment-integration-service/service.yaml
  - carrier-mock-service/deployment.yaml
  - carrier-mock-service/service.yaml
  - qa-service/deployment.yaml
  - qa-service/service.yaml
  - infra/rabbitmq.yaml
  - infra/keycloak.yaml
  - infra/kong.yaml
  - infra/prometheus-grafana.yaml
  - infra/efk.yaml