global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8001']

  - job_name: 'shipment-integration-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shipment-integration-service:8002']

  - job_name: 'carrier-mock-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['carrier-mock-service:8003']

  - job_name: 'qa-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['qa-service:8004']
